### PR TITLE
MSMQ support added to CQRS demo 

### PR DESCRIPTION
**Pull request by kfrajtak**
Hi, I really liked your demo, but did not wanted to use RabbitMQ and install Erlang, so I did some refactoring and added MSMQ adapter to your code.
I have created this pull request in case you'd like it and would like to add it to your code base.

Here's the summary
- RabbitMQ code refactored and moved into separate assembly
- MSMQ adapter added
- more NLog logging added

Regards,
Karel Frajtak

### CODE REVIEW

**Comment by sachabarber** [comment]
Sorry only just saw this, must have disappeared into my email void. I will review this and merge when I have looked at it. Thanks

**Comment by kfrajtak** [comment]
No problem :)

**Comment by minhhungit** [comment]
@kfrajtak  : Did you commit all files, I can not find your project
image

Can you check it again, thank you

**Comment by kfrajtak** [comment]
In my clone (year 2015) there is no Bus directory, but there is BusAdapters directory.

**Comment by minhhungit** [comment]
@kfrajtak  yes that image is your project (2015) but I still don't see any folder like BusAdapters.
Can you take a screenshot, thanks !

**Comment by minhhungit** [comment]
@kfrajtak look you did not commit BusAdapters folder
image

**Comment by kfrajtak** [comment]
I see, sorry. I'll fix it.

**Comment by kfrajtak** [comment]
Have a look at it now. Sorry for the trouble.

**Comment by sachabarber** [comment]
Merged it

**Comment by minhhungit** [comment]
lol, a PR ~3 years old, thank you @kfrajtak , @sachabarber

**Comment by sachabarber** [comment]
Ha it still made it in

**Pull request merged**
